### ISSUE TITLE
Question about orientation of ICs

### ISSUE THREAD

**Issue by ezcGman** [jsanpe/c2c-64#4]
Hey there (again) :)

I was just about to solder one of these and then realized that the PCB is missing the usual dot indicators to tell about the orientation of the ICs. I saw that the silkscreen/graveyard on one side is open instead of closed. Is that the orientation indicator?

Talking about this:
![2016_0101_015052_001](https://github.com/jsanpe/c2c-64/assets/3090131/fa1f0aab-8563-4a4a-85ce-90a948185e92)

Thanks and greetings,

Andy!

**Comment by jsanpe** [comment]
Yup, Kicad's default footprints indicate pin number 1 using the open angle, as you mentioned

**Comment by ezcGman** [comment]
Ou, never realized. I also use KiCAD but that I never saw.
Thanks!! Off to the workbench then \o/
