### ISSUE TITLE
PCB silkscreen or IBOM suggestions

### ISSUE THREAD

**Issue by ezcGman** [jsanpe/c2c-64#6]
Hey again :D

While building the board, I realized a few places where the PCB and the IBOM was missing orientational indicators for a few parts. I was able to sort it out by multimetering, but still wanted to leave the suggestions here:

* The radial caps are missing orientation / GND indicators
* The SMD LEDs are also missing the orientation / GND indicators
* The resistor array has an orientation indicator, but it doesn't need one
* MAYBE improve the orientation indicator for the ICs, away from the single / open graveyard silkscreen to the typical dot?
* Bring the UART pin namings to the back, as you can't read them anymore when a pin header is soldered on?
* You have a few overlapping silkscreens, like U8 and R16, or C11 & C19, etc. They also have different font sizes, maybe making them all the smaller size gives you the space needed?
* C2, C7, C12, C17 have a different footprint assigned (the hand solder footprint) than all the other caps and resistors. So in the IBOM you now have the 22uF 0805 caps listed separately. Quite confusing when you order components and place them, as they're listed twice now ;)

That's it :D I just close it right away; you can just ignore if you want, just wanted to bring them up ;)

**Comment by jsanpe** [comment]
Thanks for the feedback, I'll keep it in mind for the next project update.
